language: go
install: true
services:
  - mongodb
  - postgresql
go:
  - 1.10.x
  - master
before_script:
  - psql -c 'create database data;' -U postgres
script:
  - 'make ${JOB}'
env:
  global:
    - GOARCH=amd64
  matrix:
    - JOB=test
    - JOB=race
    - JOB=default
    - JOB=frontend/test
    - JOB=frontend/build
jobs:
  fast_finish: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
