language: go
install: true
go:
  - 1.10.x
  - master
script:
  - 'make ${JOB}'
env:
  global:
    - GOARCH=amd64
  matrix:
    - JOB=test
    - JOB=race
    - JOB=default
jobs:
  fast_finish: true
after_success:
  - bash <(curl -s https://codecov.io/bash)