/**
 * DBqueryBench
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DBqueryBench);
  }
}(this, function(expect, DBqueryBench) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DBqueryBench.QueryApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QueryApi', function() {
    describe('addQuery', function() {
      it('should call addQuery successfully', function(done) {
        //uncomment below and update the code to test addQuery
        //instance.addQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('approveQuery', function() {
      it('should call approveQuery successfully', function(done) {
        //uncomment below and update the code to test approveQuery
        //instance.approveQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteApprovalQuery', function() {
      it('should call deleteApprovalQuery successfully', function(done) {
        //uncomment below and update the code to test deleteApprovalQuery
        //instance.deleteApprovalQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteQuery', function() {
      it('should call deleteQuery successfully', function(done) {
        //uncomment below and update the code to test deleteQuery
        //instance.deleteQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findQueryByOwner', function() {
      it('should call findQueryByOwner successfully', function(done) {
        //uncomment below and update the code to test findQueryByOwner
        //instance.findQueryByOwner(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findQueryByStatus', function() {
      it('should call findQueryByStatus successfully', function(done) {
        //uncomment below and update the code to test findQueryByStatus
        //instance.findQueryByStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getQueries', function() {
      it('should call getQueries successfully', function(done) {
        //uncomment below and update the code to test getQueries
        //instance.getQueries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getQueryById', function() {
      it('should call getQueryById successfully', function(done) {
        //uncomment below and update the code to test getQueryById
        //instance.getQueryById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateQuery', function() {
      it('should call updateQuery successfully', function(done) {
        //uncomment below and update the code to test updateQuery
        //instance.updateQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
