/**
 * DBqueryBench
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DBqueryBench);
  }
}(this, function(expect, DBqueryBench) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DBqueryBench.QueryApprovals();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QueryApprovals', function() {
    it('should create an instance of QueryApprovals', function() {
      // uncomment below and update the code to test QueryApprovals
      //var instance = new DBqueryBench.QueryApprovals();
      //expect(instance).to.be.a(DBqueryBench.QueryApprovals);
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new DBqueryBench.QueryApprovals();
      //expect(instance).to.be();
    });

    it('should have the property approve (base name: "approve")', function() {
      // uncomment below and update the code to test the property approve
      //var instance = new DBqueryBench.QueryApprovals();
      //expect(instance).to.be();
    });

  });

}));
