/**
 * DBqueryBench
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.DBqueryBench) {
      root.DBqueryBench = {};
    }
    root.DBqueryBench.QueryApprovals = factory(root.DBqueryBench.ApiClient, root.DBqueryBench.User);
  }
}(this, function (ApiClient, User) {
  'use strict';




  /**
   * The QueryApprovals model module.
   * @module model/QueryApprovals
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>QueryApprovals</code>.
   * @alias module:model/QueryApprovals
   * @class
   */
  var exports = function () {
    var _this = this;



  };

  /**
   * Constructs a <code>QueryApprovals</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QueryApprovals} obj Optional instance to populate.
   * @return {module:model/QueryApprovals} The populated <code>QueryApprovals</code> instance.
   */
  exports.constructFromObject = function (data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('user')) {
        obj['user'] = User.constructFromObject(data['user']);
      }
      if (data.hasOwnProperty('approved')) {
        obj['approved'] = ApiClient.convertToType(data['approved'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/User} user
   */
  exports.prototype['user'] = undefined;
  /**
   * @member {Boolean} approve
   */
  exports.prototype['approved'] = undefined;



  return exports;
}));


