/**
 * DBqueryBench
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DBqueryBench) {
      root.DBqueryBench = {};
    }
    root.DBqueryBench.QueryResults = factory(root.DBqueryBench.ApiClient);
  }
}(this, function (ApiClient, User) {
  'use strict';




  /**
   * The QueryResult model module.
   * @module model/QueryResult
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>QueryResult</code>.
   * @alias module:model/QueryResult
   * @class
   */
  var exports = function () {
    var _this = this;



  };

  /**
   * Constructs a <code>QueryResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QueryResult} obj Optional instance to populate.
   * @return {module:model/QueryResult} The populated <code>QueryResult</code> instance.
   */
  exports.constructFromObject = function (data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('affectedrows')) {
        obj['affectedrows'] = ApiClient.convertToType(data['affectedrows'], 'Integer');
      }
      if (data.hasOwnProperty('success')) {
        obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} affectedrows
   */
  exports.prototype['affectedrows'] = undefined;
  /**
   * @member {Boolean} success
   */
  exports.prototype['success'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


