/*
 * DBworkBench
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

import (
	"encoding/json"
	"io"
	"io/ioutil"
	"sort"

	"github.com/gfleury/squaas/config"
)

type Server struct {
	Name string `json:"name" bson:"name"`

	Uri string `json:"uri,omitempty" bson:"uri"`

	FailedRetries int

	LastErrors []string
}

type Servers []Server

func (u *Server) Byte() (objBytes []byte, err error) {
	return json.Marshal(u)
}

func (u *Servers) Byte() (objBytes []byte, err error) {
	return json.Marshal(u)
}

func (u *Server) Merge(eu *Server) (err error) {
	return err
}

func (u *Servers) Parse(bodyReader io.Reader) error {
	body, err := ioutil.ReadAll(bodyReader)
	if err != nil {
		return err
	}

	return json.Unmarshal(body, u)
}

func (u *Server) Parse(bodyReader io.Reader) error {
	body, err := ioutil.ReadAll(bodyReader)
	if err != nil {
		return err
	}

	return json.Unmarshal(body, u)
}

func GetDatabases(allData bool) Servers {
	databases := config.GetConfig().GetStringMapString("databases")
	servers := Servers{}

	for server := range databases {
		database := Server{Name: server}
		if allData {
			database.Uri = databases[server]
		}
		servers = append(servers, database)
	}

	sort.Slice(servers, func(i, j int) bool {
		return servers[i].Name < servers[j].Name
	})
	return servers
}
