/*
 * DBworkBench
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

import (
	"encoding/json"
	"io"
	"io/ioutil"
)

type User struct {
	Name string `json:"name" bson:"name"`
}

func (u *User) Byte() (objBytes []byte, err error) {
	return json.Marshal(u)
}

func (u *User) Merge(eu *User) (err error) {
	return err
}

func (u *User) Parse(bodyReader io.Reader) error {
	body, err := ioutil.ReadAll(bodyReader)
	if err != nil {
		return err
	}

	return json.Unmarshal(body, u)
}
